// Build-time float math is expected here (the table is *rounded* to
// integers — see the module note); the precision-loss lint is noise.
#![allow(clippy::cast_precision_loss, clippy::cast_possible_truncation)]

//! Bakes the sine lookup table and the angle constants used by
//! `src/trig.rs` as Q32.32 integer (`i64`) literals.
//!
//! Determinism argument: the table is computed here with `f64`, but
//! every value is *rounded to the nearest Q32.32 step* (~2.33e-10).
//! A correctly-rounded `sin` is accurate to well under 1e-15, so the
//! rounded integer is identical across any conforming libm — the
//! cross-platform `sin`/`fma`/`x87` divergences that DESIGN.md §3.1
//! warns about are all far below the rounding step and cannot change
//! a single table entry. At *runtime* the table is consumed only with
//! integer arithmetic (lookup + fixed-point lerp in `trig.rs`), so no
//! float ever touches the sim. The table is therefore deterministic
//! both at build time (reproducible) and at run time (integer-only).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Number of samples across one full turn `[0, 2*pi)`. Power of two;
/// 4096 entries give < 1e-3 max error after lerp, ample for sim use
/// and cheap to bake (32 KiB of `i64`).
const LUT_LEN: usize = 4096;

/// `2^32`, the Q32.32 scale factor.
const SCALE: f64 = 4_294_967_296.0;

/// Round a real value to its nearest Q32.32 raw `i64`.
fn to_fixed(x: f64) -> i64 {
    // `round` is round-half-away-from-zero; the half-step ambiguity it
    // resolves is itself ~1e-10 wide and never lands on a libm-visible
    // boundary for these inputs.
    (x * SCALE).round() as i64
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out_dir).join("trig_tables.rs");

    let pi = std::f64::consts::PI;
    let tau = std::f64::consts::TAU;
    let frac_pi_2 = std::f64::consts::FRAC_PI_2;

    let mut src = String::with_capacity(LUT_LEN * 16 + 512);
    src.push_str("// @generated by build.rs — do not edit.\n");
    let _ = writeln!(src, "pub(crate) const LUT_LEN: usize = {LUT_LEN};");
    let _ = writeln!(src, "pub(crate) const PI_BITS: i64 = {};", to_fixed(pi));
    let _ = writeln!(src, "pub(crate) const TAU_BITS: i64 = {};", to_fixed(tau));
    let _ = writeln!(
        src,
        "pub(crate) const FRAC_PI_2_BITS: i64 = {};",
        to_fixed(frac_pi_2)
    );

    let _ = writeln!(src, "pub(crate) const SIN_LUT: [i64; {LUT_LEN}] = [");
    for i in 0..LUT_LEN {
        let angle = (i as f64) / (LUT_LEN as f64) * tau;
        let _ = writeln!(src, "    {},", to_fixed(angle.sin()));
    }
    src.push_str("];\n");

    fs::write(&dest, src).expect("write trig_tables.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
